-- =============================================================================
-- STEP — sfa_step additions DDL (tables missing from the initial sfa_step_ddl.sql)
-- Run AFTER sfa_step_ddl.sql. Safe to re-run (all CREATE TABLE IF NOT EXISTS).
-- Project: skintific-data-warehouse  Dataset: sfa_step
-- =============================================================================

-- =============================================================================
-- SYNC_WATERMARK
-- Referenced by sp_refresh_fact_management_target and sp_refresh_fact_visit_sadata
-- but missing from the original DDL. Must exist before calling any sp_refresh_*.
-- =============================================================================
CREATE TABLE IF NOT EXISTS `skintific-data-warehouse.sfa_step.sync_watermark` (
  sync_table_name      STRING    NOT NULL OPTIONS(description="Name matching the WHERE clause in sp_refresh_* procedures, e.g. 'fact_management_target', 'fact_visit_sadata'"),
  last_watermark_value STRING             OPTIONS(description="Last processed watermark as a string — cast at read time (DATE for date-based syncs)"),
  last_run_at          TIMESTAMP          OPTIONS(description="Wall-clock time the last sync job completed"),
  last_run_status      STRING             OPTIONS(description="'success' | 'error'"),
  error_message        STRING             OPTIONS(description="Populated only when last_run_status = 'error'"),
  PRIMARY KEY (sync_table_name) NOT ENFORCED
)
OPTIONS (description = "Incremental sync watermarks for sp_refresh_* procedures. One row per synced table.");

-- Seed initial watermarks so procedures don't crash on first run
-- (reads SAFE_CAST(NULL AS DATE) → NULL, then the WHERE clause uses IS NULL safe math)
INSERT INTO `skintific-data-warehouse.sfa_step.sync_watermark`
  (sync_table_name, last_watermark_value, last_run_at, last_run_status)
VALUES
  ('fact_management_target', '2024-01-01', NULL, NULL),
  ('fact_visit_sadata',      '2024-01-01', NULL, NULL)
;

-- =============================================================================
-- USERS
-- STEP application users for login. Passwords stored as bcrypt hashes — the
-- FastAPI backend generates them via passlib. Never store plaintext here.
-- Seed at least one HO Admin manually after running this DDL:
--   python -c "from passlib.hash import bcrypt; print(bcrypt.hash('your-password'))"
-- then INSERT one row for the first HO Admin before first login.
-- =============================================================================
CREATE TABLE IF NOT EXISTS `skintific-data-warehouse.sfa_step.users` (
  user_id           STRING    NOT NULL OPTIONS(description="UUID generated at INSERT time"),
  username          STRING    NOT NULL OPTIONS(description="Login handle — must be unique, enforced at app layer"),
  email             STRING,
  password_hash     STRING    NOT NULL OPTIONS(description="bcrypt hash via passlib[bcrypt] — never store plaintext"),
  role              STRING    NOT NULL OPTIONS(description="'ho_admin' | 'area_manager' | 'spv' | 'distributor_admin' | 'salesman' — maps to STEP.ROLES in step.js"),
  territory         STRING             OPTIONS(description="Region/area name for scope-limited roles (area_manager, spv). NULL for national roles."),
  distributor_code  STRING             OPTIONS(description="e.g. 'DST171' — set for distributor_admin role, NULL for others"),
  is_active         BOOL      NOT NULL OPTIONS(description="FALSE = soft-deleted / suspended"),
  created_at        TIMESTAMP NOT NULL OPTIONS(description="CURRENT_TIMESTAMP() at INSERT"),
  last_login        TIMESTAMP          OPTIONS(description="Updated on every successful /auth/login response"),
  PRIMARY KEY (user_id) NOT ENFORCED
)
OPTIONS (description = "STEP app users table. See backend/services/auth.py for password hashing. Seed first HO Admin manually after DDL runs.");

-- =============================================================================
-- APPROVALS
-- Multi-stage approval workflow records.
-- payload_json stores the full request data as a JSON string — no typed columns
-- per approval type, so the schema stays stable as new approval types are added.
-- =============================================================================
CREATE TABLE IF NOT EXISTS `skintific-data-warehouse.sfa_step.approvals` (
  approval_id    STRING    NOT NULL OPTIONS(description="UUID, generated by backend at submit time"),
  approval_type  STRING    NOT NULL OPTIONS(description="'target_adjustment' | 'tier_override' | 'route_change' | 'salesman_add'"),
  entity_id      STRING             OPTIONS(description="ID of the entity being approved (salesman_id, target_sk, etc.)"),
  entity_type    STRING             OPTIONS(description="'SALESMAN' | 'TARGET' | 'ROUTE'"),
  submitted_by   STRING    NOT NULL OPTIONS(description="user_id of the submitter"),
  submitted_at   TIMESTAMP NOT NULL,
  status         STRING    NOT NULL OPTIONS(description="'pending' | 'approved' | 'rejected' | 'cancelled'"),
  current_stage  STRING             OPTIONS(description="Current stage label, e.g. 'spv', 'am', 'dm'"),
  reviewed_by    STRING             OPTIONS(description="user_id of the last person to act on this"),
  reviewed_at    TIMESTAMP,
  notes          STRING             OPTIONS(description="Reviewer's notes — displayed in the Approval detail view"),
  payload_json   STRING    NOT NULL OPTIONS(description="Full request payload as a JSON string — content varies per approval_type"),
  created_at     TIMESTAMP NOT NULL,
  updated_at     TIMESTAMP,
  PRIMARY KEY (approval_id) NOT ENFORCED
)
PARTITION BY DATE(submitted_at)
CLUSTER BY status, approval_type
OPTIONS (description = "STEP approval workflow records. Append-mostly — status updates are the only mutations post-insert.");

-- =============================================================================
-- ROUTE_ASSIGNMENT
-- Store-Salesman-Route assignments uploaded via Import & Export → Penugasan Route.
-- Each upload is one batch (shared batch_id). The STEP backend reads this table
-- to reflect committed assignments back into the Route Planner and salesman views.
-- =============================================================================
CREATE TABLE IF NOT EXISTS `skintific-data-warehouse.sfa_step.route_assignment` (
  assignment_id       STRING    NOT NULL OPTIONS(description="UUID per row, generated at upload commit time"),
  distributor_code    STRING    NOT NULL,
  outlet_sk           STRING             OPTIONS(description="FK to dim_outlet — NULL if kode_toko couldn't be resolved at upload time"),
  source_outlet_code  STRING    NOT NULL OPTIONS(description="Raw kode_toko from the uploaded Excel row"),
  store_name          STRING,
  salesman_sk         STRING             OPTIONS(description="FK to dim_salesman — NULL if salesman_id couldn't be resolved"),
  source_salesman_id  STRING    NOT NULL OPTIONS(description="Raw salesman_id from the uploaded Excel row"),
  route_code          STRING,
  route_name          STRING,
  action              STRING    NOT NULL OPTIONS(description="'ASSIGN' | 'REASSIGN' | 'REMOVE'"),
  effective_date      DATE      NOT NULL OPTIONS(description="First date this assignment takes effect"),
  uploaded_by         STRING    NOT NULL OPTIONS(description="user_id of the person who committed the upload"),
  uploaded_at         TIMESTAMP NOT NULL,
  batch_id            STRING    NOT NULL OPTIONS(description="UUID shared across all rows in the same upload batch — use to query or roll back a batch"),
  PRIMARY KEY (assignment_id) NOT ENFORCED
)
PARTITION BY effective_date
CLUSTER BY distributor_code, salesman_sk
OPTIONS (description = "Store-Salesman-Route assignments from Penugasan Route bulk uploads. One row per Excel data row per commit.");
